### ISSUE TITLE
Installation sous Androïd

### ISSUE THREAD

**Issue by Glaived** [Laarks/poke-strings#1]
Plop,

comment installer les strings sous Androïd ? Étant nouveau dans la sphère PokéMMO je ne sais pas comment m'y prendre

**Comment by Laarks** [comment]
Salut,

Je suis en train de faire des tests sans Android. Ca ne marche pas correctement sur Android. Une version adaptée mobile arrive.

**Comment by Laarks** [comment]
Je viens d'ajouter d'ajouter une version Android. Il y a un seul fichier a importer. Il suffit d'aller dans la gestion de client sur l'ecran de connexion et de cliquer sur "Importer le fichier de Strings" Et d'aller sélectionner mon fichier dans le dossier Android.
